apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goweb-app
  {{- if .Values.labels }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: "server.example.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goweb-app
                port:
                  number: 8080
